version: '3.7'

services:

 flask_server:
  container_name: flask_server
  ports:
    - '8000:5000' #jupyterhub
  build:
    context: ./
    dockerfile: Dockerfile
  user: root
  restart: always
  depends_on:
      - mysql
  volumes:
    - ./:/flask_docker/
 
 mysql:
  image: mysql:5.7
  environment:
      MYSQL_DATABASE: flask_db
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
  expose:
      - 3306
  volumes:
    - flask_db_data:/var/lib/mysql
    - ./mysql-dump:/docker-entrypoint-initdb.d
  restart: always
  ports:
    - '127.0.0.1:3308:3306'

volumes:
  flask_db_data: